from typing import List

from langchain_core.tools import BaseTool
from langchain_google_community.gmail.toolkit import GmailToolkit
from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build

# Must list all scopes originally granted in the OAuth flow so that token
# refresh doesn't narrow the stored scopes and break other tools.
_SCOPES = [
    "https://mail.google.com/",
    "https://www.googleapis.com/auth/drive",
]


def get_gmail_tools() -> List[BaseTool]:
    """
    Initializes and returns the Gmail toolkit tools.
    Requires token.json (generated by scripts/local_auth_google.py) in the project root.
    Loads credentials directly to avoid langchain's get_gmail_credentials overwriting
    token.json with a narrowed scope list.
    """
    try:
        creds = Credentials.from_authorized_user_file("token.json", _SCOPES)
        api_resource = build("gmail", "v1", credentials=creds)
        toolkit = GmailToolkit(api_resource=api_resource)
        return toolkit.get_tools()
    except Exception as e:
        print(f"Error initializing Gmail tools: {e}")
        return []
